apiVersion: v1
kind: Secret
metadata:  
  name: backend-app-secret
type: Opaque
data:
  mysql_user: ZGV2b3Bz
  db_passwd: cGFzc3dvcmQ=
  mysql_host: <BASE64_ENCODED_IP_FOR_mysql-db>
  db_name: ZGVtbw==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-deployment
  labels:
    app: backend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: jswolf059/developer-utilities-backend
          ports:
            - containerPort: 5000
          env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                name: backend-app-secret
                key: mysql_host
                optional: false
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: backend-app-secret
                key: mysql_user
                optional: false 
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-app-secret
                key: db_passwd
                optional: false 
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: backend-app-secret
                key: db_name
                optional: false 
      imagePullSecrets:
      - name: docker-hub-creds
---

apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  selector:
    app: backend-app
  ports:
    - name: web-app-port
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
